spring.application.name=wishmegift

# # Décommenter lors de la mise en place de la base de données
# # Changer les identifiants de la base de données ici
# spring.datasource.url=jdbc:postgresql://localhost:5432/database-name
# spring.datasource.username=dbuser
# spring.datasource.password=dbpassword
# spring.jpa.hibernate.ddl-auto=create

# # Décommenter pour afficher les requêtes SQL réalisées
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
